services:
  - type: web
    name: baklovah-web
    runtime: node
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: "/"
    envVars:
      # Runtime
      - key: NODE_ENV
        value: production

      # Database (use either DATABASE_URL or individual params below)
      - key: DATABASE_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_SSL
        value: "true"
      - key: DB_SSL_REJECT_UNAUTHORIZED
        value: "true"

      # Auth / sessions
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true

      # Admin bootstrap
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        value: admin@example.com

      # Stripe (optional if pay-at-pickup only)
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false

      # AWS S3
      - key: AWS_ACCESS_KEY
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: S3_BUCKET_NAME
        sync: false
